{% set name = "keras-metrics" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/keras-metrics-{{ version }}.tar.gz
  sha256: e65b8ace5f4d2100452d3109ef755870f1cfc00d13cb6d8eb96084aee2f5efa2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - keras
    - pip
    - python {{ python_min }}
    - tensorflow
  run:
    - keras >=2.1.5
    - python >={{ python_min }}
    - scikit-learn >=0.20.2
    - tensorflow >=1.8.0

test:
  imports:
    - keras_metrics
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/netrack/keras-metrics
  summary: Metrics for Keras model evaluation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
